### ISSUE TITLE
Disable compaction?

### ISSUE THREAD

**Issue by bluealbin** [syndtr/goleveldb#100]
Is there a way to disable the compaction? So the writer is not blocked while bulk inserts.

**Comment by syndtr** [comment]
Unfortunately no. But you can minimize *table compaction run* and *write thortle* by increasing the value of  `CompactionL0Trigger`, `WriteL0PauseTrigger` and `WriteL0SlowdownTrigger`.

**Comment by bluealbin** [comment]
thanks.
Is it feasible to dynamically change such triggers while the leveldb  is in long-run?  so  I can set big triggers for foreseeable bulk inserts?

**Comment by syndtr** [comment]
Yes, that shouldn't be an issue.

**Comment by fghanadi** [comment]
> Unfortunately no. But you can minimize _table compaction run_ and _write thortle_ by increasing the value of `CompactionL0Trigger`, `WriteL0PauseTrigger` and `WriteL0SlowdownTrigger`.

Hi, Can you explain how can I change default values of `CompactionL0Trigger`, ` WriteL0PauseTrigger` and `WriteL0SlowdownTrigger` and what's the optimized value of them to speed up writing to db.
