### ISSUE TITLE
fsync: invalid argument

### ISSUE THREAD

**Issue by GannicusLiu** [syndtr/goleveldb#103]
After I put about sixty thousand records  to the leveldb,then leveldb throw a exception:fsync: invalid argument.
Anyone knows how to fix this problem?

**Comment by syndtr** [comment]
What is your OS?

**Comment by GannicusLiu** [comment]
My host machine is  win7 system,but I use vagrant install a centos in my virtual machine. The host machine of a disk is mapped to a virtual machine.my go program is located in this dir.my go program is running in centos.

**Comment by balboah** [comment]
This happens if you run in a docker container through boot2docker with a mounted volume which runs on VirtualBox. The volume is shared with the host os and I guess low level filesystem calls doesn't work here.
Would be awesome if it could be worked around in these cases

**Comment by mintzhao** [comment]
still has the problem

**Comment by RobertDiebels** [comment]
@mintzhao @balboah  Can confirm. Having this problem as well.

Host OS: Windows 10 Home
Virtualbox: 5.2.6 r120293
Minikube: v0.25.0

Using a Hyperledger Burrow container which has LevelDB as a dependency. 

Please reopen.
