### ISSUE TITLE
Log file size breaking goleveldb

### ISSUE THREAD

**Issue by AudriusButkevicius** [syndtr/goleveldb#104]
As per: https://forum.syncthing.net/t/log-file-too-big-prevented-syncthing-from-starting/2532
leveldb.OpenFile returns
```
read /Users/andrew/Library/Application Support/Syncthing/index/010489.log: result too large
```
Seems to be OSX

**Comment by syndtr** [comment]
This seems to be caused by filesystem corruption.

https://discussions.apple.com/thread/974231?tstart=0

> *Results too large* basically means that the source file's indicated size won't fit on the destination, given the free space. Often, it also means the folder information on the source is damaged and should be repaired...
