### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by joeblew99** [syndtr/goleveldb#105]
Is it possible to run on android now that go supports android ,?

**Comment by AudriusButkevicius** [comment]
syncthing was using this library on android fine (in a binary form), just need to compile the binary for linux/arm.

I don't think you can embed this into a java application, unless you resort to some JNI magic.

**Comment by joeblew99** [comment]
@AudriusButkevicius 

gomobile should be able to compile it, and then the standard Xcode & Android tools are used to make the UI, and the DB should be packaged in with it.

I dont have time to try right now. For BoltDB it does work though.
