### ISSUE TITLE
Open read only?

### ISSUE THREAD

**Issue by calmh** [syndtr/goleveldb#107]
We're debugging some db corruption issues (https://github.com/syncthing/syncthing/issues/987 and similar), which is made more tricky by not being able to write tools to inspect the database that don't also start compaction and stuff. It seems there *is* some sort of read only mode, that you can end up in in case of errors, but there isn't a way to get there intentionally?

**Comment by syndtr** [comment]
Yes, the DB will enter ready-only mode if compaction detecting corruption. And correct, you can't trigger it intentionally, for now. Bu I can make it so, shouldn't be hard.

**Comment by calmh** [comment]
:heart:
