### ISSUE TITLE
How can I clear all data ?

### ISSUE THREAD

**Issue by wenerme** [syndtr/goleveldb#108]
Is there any way to clear all data ?

**Comment by syndtr** [comment]
What do you mean? Is there any reason by just deleting the DB files din't work for your case? This is embedded DB after all.

**Comment by wenerme** [comment]
I have to write code to locate directory and delete, is kind of fussy.It's better to have a clear method, I thinks this is an common use case.

**Comment by syndtr** [comment]
> I have to write code to locate directory and delete, is kind of fussy.

It is quite simple actually.

	db, err := leveldb.OpenFile("path/to/db", nil)
	// do somehing ...
	db.Close()
	os.RemoveAll("path/to/db")

> It's better to have a clear method, I thinks this is an common use case.

I don't think so. Well, at least for embedded key/value database such as leveldb.
Adding such method would add clutter without real advantage, except for shorten few line of code, which is not worth it.
