### ISSUE TITLE
db.Delete() doesn't return an error if DB doesn't contain the key

### ISSUE THREAD

**Issue by akalin** [syndtr/goleveldb#109]
https://godoc.org/github.com/syndtr/goleveldb/leveldb#DB.Delete says:

`Delete deletes the value for the given key. It returns ErrNotFound if the DB does not contain the key.`

Repro case:

```
package main

import (
	"fmt"

	"github.com/syndtr/goleveldb/leveldb"
)

func main() {
	db, err := leveldb.OpenFile("test_db", nil)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	err = db.Delete([]byte("test"), nil)
	fmt.Printf("err = %v\n", err)
}
```

```
> ./test_leveldb 
err = <nil>
```

**Comment by syndtr** [comment]
This is error in documentation. Aparently this can't be done in leveldb, since deleting key actually just mark those key for deletion. I will fix this.
