### ISSUE TITLE
Clearing the cache so subsequent Gets have to fetch from persistence

### ISSUE THREAD

**Issue by TomOgoma** [syndtr/goleveldb#120]
Hi,

When testing my application of the library, sometimes I do an "os.RemoveAll" call on the db folder in order to quickly clear the db and start the next test. I however found that some data still exists (in the cache?) ...so I end up having to implement some hacky code where I close and reopen the db in order to continue. Is there a way to clear the cache after performing such an IO operation? Of course this hack only exists in my tests but I'd like to keep them clean too. Here is an example of what I'm trying to achieve

```
//  lets call my question CacheClearing :-)
func TestCacheClearing(t *testing.T) {

	//  Set up
	db, _ := leveldb.OpenFile("testCache.db", nil)
	db.Put([]byte("some-key"), []byte("some data"), nil)

	//  Manually delete all ...probably a huge Sin to do this in production code
	if err := os.RemoveAll("testCache.db"); err != nil { panic(err) }

	// Is there a way to clear the cache at this point?
	// Here is what I've tried/played with:
	// cacher := opt.GetBlockCacher() // assuming I had done leveldb.OpenFile("filename", opt)
	// cache := cache.NewCache(nil) // opt.Cacher '!=' cache.Cacher so not valid arg here
	// cache.EvictAll()
	// ...as expected (I'm assuming since I cannot access the cache from opt),
	// This is not possible, maybe I'm doing this part wrong?

	// This part fails (gets into the err == nil condition)
	retrVal, err := db.Get([]byte("some-key"), nil)
	if err == nil {
		retrStr := string (retrVal)
		t.Error("Expected an error from empty db but got: " + retrStr)
		t.FailNow()
	}

	t.Logf("Got error as expected %s", err.Error())
}
```

**Comment by syndtr** [comment]
Well, this is hacky in the first place, you're not supposed to remove the db files while the db's still open (goleveldb depends on this, i.e. that the files only modified by goleveldb). The "right" way to do is to close the db, remove the files, and reopen the db.

Btw, leveldb not just cache blocks, but also lots of things, like manifest data, open files, etc. It also buffers recently written data into temporary in-memory datastore called "memdb".
