### ISSUE TITLE
errors.IsCorrupted not "wide" enough?

### ISSUE THREAD

**Issue by calmh** [syndtr/goleveldb#121]
I'm using `errors.IsCorrupted` at database open time to decide whether an error is something we should try recover on (in worst case dropping the database and reinitializing if the recover doesn't work), or if it is something like the database already being locked. However, there seems to be corruption related errors that aren't covered by that convenience function. For example [this](https://github.com/syndtr/goleveldb/blob/master/leveldb/storage/file_storage.go#L246) gets returned verbatim and [ErrMissingFiles](https://github.com/syndtr/goleveldb/blob/master/leveldb/errors/errors.go#L61) looks like it may not trigger `IsCorrupted` as well? Is this intentional in that those types of corruption are per definition unrecoverable or something? As is it seems I need to to string matching on the returned error even in the presence of the useful-sounding `IsCorrupted`. :)

**Comment by syndtr** [comment]
You're right `errors.IsCorrupted` should also covering corruption due to missing files, as `Recover` is able to recover the db from this kind of corruption.

**Comment by syndtr** [comment]
Oh, I just realized that `ErrMissingFiles` always wrapped with `ErrCorrupted`.
