### ISSUE TITLE
change DefaultComparer

### ISSUE THREAD

**Issue by leedstyh** [syndtr/goleveldb#125]
I use golevedb as a time series store by setting the keys like `xxx_20151113`. Now I have to store & iter the db reversely to get the "latest x items".

I write my own comparer but can't assign it to `comparer.DefaultComparer`, because `comparer.DefaultComparer` is a `type reverseComparer`, not a interface `Comparer`.

Thinking change `var DefaultComparer = bytesComparer{}` to `var DefaultComparer Comparer = bytesComparer{}` should fix this.

Sorry for my poor Engiish!

**Comment by leedstyh** [comment]
Ok, forget this, I find the way to iter reversely.

**Comment by syndtr** [comment]
You can override default comparer using options. `Options.Comparer` to be exact.
