### ISSUE TITLE
How to get disk space back after massive bulk delete operation?

### ISSUE THREAD

**Issue by bogdanovich** [syndtr/goleveldb#127]
I have a db with 0 keys (all keys were deleted previously), but it still takes 1.4Gb of disk space.
I scan for the first and last elements on startup and it takes about 1 minute to execute this:

```go
if iter.First() {
	q.head = q.dbKeyToID(iter.Key()) - 1
} else {
	q.head = 0
}

if iter.Last() {
	q.tail = q.dbKeyToID(iter.Key())
} else {
	q.tail = 0
}

return iter.Error()
```

and in the end both `q.head` and `q.tail` are equal 0.
Seems like it scans though all of 1.4Gb tombstones and finds nothing.
Should I manually compact them or there is a better way to deal with old deleted keys?

**Comment by syndtr** [comment]
The `deletion marker` probably still dangling in the `memdb`, if you stop writing then size threshold won't be reached, so it will not get flushed, hence auto compaction won't kick-in. If this the case then manual compaction is the only way to force compaction.

**Comment by bogdanovich** [comment]
I'm implementing a leveldb-based queue with headID and tailID. Writes are append-only with auto-increment keys. All deletes are also sequential. Once value read and used - it's get deleted. So in this type of workload old .ldb files are never get deleted even if I continue writing. I have 13,000 of ldb files (15GB) and most of keys are already deleted. 

In this situation, what is the best strategy to manually compact the database?
I can count totalBytesDeleted from DB and trigger CompactRange(0, q.head - 1) after each 10Mb get deleted. Is that viable solution?

**Comment by bogdanovich** [comment]
Here is the sample I wrote to reproduce the issue: https://gist.github.com/bogdanovich/d5aeb34b523dc9cb8fb1

Old deleted keys are never get removed from the disk and disk usage is growing infinitely.

**Comment by syndtr** [comment]
@bogdanovich Thanks for the sample code. This turns out to be a bug.

**Comment by syndtr** [comment]
Unfortunately this won't reclaim space of the old DB, you still need to manually compact them once, after that you're good to go.

**Comment by bogdanovich** [comment]
Thanks for the quick fix.
