### ISSUE TITLE
New transactions seem to frequently result in corruption

### ISSUE THREAD

**Issue by davecgh** [syndtr/goleveldb#133]
I have been using the new transaction infrastructure and ran into an issue several times now where I get a "file missing" error when opening the database.  Running `leveldb.Recover` results in a corrupt database.  In each case, I have completely nuked the database and started from scratch, but it seems to always end up with this issue after enough use.

Here is the LOG:

```
=============== Feb 22, 2016 (CST) ===============
09:39:24.160455 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
09:39:25.410114 version@stat F·[10 59 600 5241 2491] S·15GiB[36MiB 84MiB 999MiB 9GiB 4GiB] Sc·[2.50 0.84 1.00 1.00 0.05]
09:39:25.421115 db@open opening
09:39:25.464621 journal@recovery F·1
09:39:25.466121 journal@recovery recovering @350921
09:39:25.471622 version@stat F·[10 59 600 5241 2491] S·15GiB[36MiB 84MiB 999MiB 9GiB 4GiB] Sc·[2.50 0.84 1.00 1.00 0.05]
09:39:25.569134 db@janitor table missing @451858
```

It's a large database, but I'll try to keep it around for a while in case you need more details.

**Comment by davecgh** [comment]
I just hit this again with a fresh database.

LOG:
```
14:06:32.565804 db@close closing
14:06:32.569305 db@close done T·3.5004ms
=============== Feb 22, 2016 (CST) ===============
14:10:24.964315 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
14:10:24.980817 version@stat F·[67 63 521 838] S·2GiB[264MiB 121MiB 998MiB 1GiB] Sc·[16.75 1.21 1.00 0.16]
14:10:24.981317 db@open opening
14:10:24.989818 journal@recovery F·1
14:10:24.990818 journal@recovery recovering @33106
14:10:24.996319 version@stat F·[67 63 521 838] S·2GiB[264MiB 121MiB 998MiB 1GiB] Sc·[16.75 1.21 1.00 0.16]
14:10:25.011821 db@janitor table missing @34477
```

Error return to application:
```
14:10:25 2016-02-22 [ERR] file missing: file missing
```

**Comment by davecgh** [comment]
Seem like I can pretty reliably reproduce this.  I hit it again and here is the full log:

[LOG.zip](https://github.com/syndtr/goleveldb/files/141572/LOG.zip)

I should also note that I'm not doing any power offs or abrupt process kills.  It is simply rapidly indexing _a lot_ of data..

**Comment by davecgh** [comment]
I've been running this for a few hours now and I haven't hit the issue again, so the fix seems to have resolved it.

Thanks for a quick response.

**Comment by syndtr** [comment]
@davecgh Thanks for the confirmation.
