### ISSUE TITLE
Significant memory usage when trying to insert data

### ISSUE THREAD

**Issue by xia0pin9** [syndtr/goleveldb#138]
I am trying to profile the memory usage of my go program, and found that the majority of memory seems to be consumed within leveldb functions (`github.com/syndtr/goleveldb/leveldb/memdb.(*DB).Put`). 

Below is the _top_ profile output:
```
(pprof) top
6815712.39kB of 6881450.49kB total (99.04%)
Dropped 372 nodes (cum <= 34407.25kB)
Showing top 10 nodes out of 28 (cum >= 242528.01kB)
      flat  flat%   sum%        cum   cum%
 6471904kB 94.05% 94.05%  6471904kB 94.05%  github.com/syndtr/goleveldb/leveldb/memdb.(*DB).Put
242528.01kB  3.52% 97.57% 242528.01kB  3.52%  bytes.makeSlice
   55040kB   0.8% 98.37%    55040kB   0.8%  lib.FP.GenerateHashMap
46004.76kB  0.67% 99.04% 54040.69kB  0.79%  main.main
  149.16kB 0.0022% 99.04% 6483852.34kB 94.22%  github.com/syndtr/goleveldb/leveldb.(*DB).Write
   68.67kB 0.001% 99.04% 319400.85kB  4.64%  main.Worker
   13.77kB 0.0002% 99.04% 6507694.47kB 94.57%  main.Worker1
    4.03kB 5.9e-05% 99.04% 6495736.37kB 94.39%  github.com/syndtr/goleveldb/leveldb.(*DB).Put
         0     0% 99.04%   196616kB  2.86%  bytes.(*Buffer).WriteString
         0     0% 99.04% 242528.01kB  3.52%  bytes.(*Buffer).grow
```

**Comment by syndtr** [comment]
What is your `WriteBuffer`? How big your batch are? Is this in-use or allocated memory? Do you on latest commit?

**Comment by syndtr** [comment]
Also could you do `list memdb.*.Put`?

**Comment by xia0pin9** [comment]
I am using the all of the default options, they are allocated memory. The list output is as follows:
```
ROUTINE ======================== github.com/syndtr/goleveldb/leveldb/memdb.(*DB).Put in /media/disks/hdd/maldata/payload/src/github.com/syndtr/goleveldb/leveldb/memdb/memdb.go
    6.17GB     6.17GB (flat, cum) 94.05% of Total
         .          .    296:		p.maxHeight = h
         .          .    297:	}
         .          .    298:
         .          .    299:	kvOffset := len(p.kvData)
         .          .    300:	p.kvData = append(p.kvData, key...)
    6.17GB     6.17GB    301:	p.kvData = append(p.kvData, value...)
         .          .    302:	// Node
         .          .    303:	node := len(p.nodeData)
    1.16MB     1.16MB    304:	p.nodeData = append(p.nodeData, kvOffset, len(key), len(value), h)
         .          .    305:	for i, n := range p.prevNode[:h] {
         .          .    306:		m := n + nNext + i
         .          .    307:		p.nodeData = append(p.nodeData, p.nodeData[m])
         .          .    308:		p.nodeData[m] = node
         .          .    309:	}
         .          .    310:
         .          .    311:	p.kvSize += len(key) + len(value)
         .          .    312:	p.n++
```

**Comment by syndtr** [comment]
How big is it your key/value pair? If it is large than `WriteBuffer` (the default is 4MiB), then `kvData` will need to grow.

**Comment by xia0pin9** [comment]
Oh, good to know that. My key is about 20B, and the value is 256KB, I only have less than 1000 such type of data insert. Another type of data has similar key size with value size 1KB, this type of data counts for about 200000 insert.

**Comment by syndtr** [comment]
Do you use batch? If you on latest commit it should switch to `transaction mode` if batch is larger than `WriteBuffer`, thus `kvData` grow should be avoided.

Also could you generate graph of the memory profile? Thanks!

**Comment by xia0pin9** [comment]
I re-installed leveldb with the latest commit, memory usage is getting better, but leveldb inserting is still the largest part of memory usage.

I am not using batch, will try it later. Attached is the new graph.
[test.pdf](https://github.com/syndtr/goleveldb/files/190768/test.pdf)

**Comment by xia0pin9** [comment]
The document says `Only one transaction can be opened at a time`. I have several workers running simultaneously, and within each worker I have multiple write operations. In this case, can I still use transaction within each worker?

**Comment by syndtr** [comment]
> I re-installed leveldb with the latest commit, memory usage is getting better, but leveldb inserting is still the largest part of memory usage.
>
> I am not using batch, will try it later. Attached is the new graph.

Wow, 3GB inuse space, that's really big, I though it was alloc space (i.e. all allocated memory since program started). This make no sense, the memdb should should be rotated long before reaching that amount of memory usage. If you on latest commit `kvData` should never need to grow in the first place (if your record record size bellow `WriteBuffer` off course). Will look into this.

> The document says Only one transaction can be opened at a time. I have several workers running simultaneously, and within each worker I have multiple write operations. In this case, can I still use transaction within each worker?

The other `OpenTransaction()` will simply blocked until current transaction are committed or discarded.  Don't use transaction if your write is small (i.e. less than `WriteBuffer`), it will saturate the compaction process. `Put()` or `Write()` will automatically switch to `transaction mode` when detecting large writes.

**Comment by syndtr** [comment]
Could you test latest commit? See if d89627bcbd64c3f7167a3136fed12d544b8071de indeed fix the issue. Thanks!

**Comment by xia0pin9** [comment]
Thanks for your update, it seems the issue has been fixed according to the attached profile graph. But when checking with linux command `htop`, it still shows the program is using about 20G residual memory during execution. And it is also strange that the memory usage (showing in `htop`) grows from about 4G to 20G within several seconds. Any suggestions for other profiling techniques? I am using [pkg/profile](https://github.com/pkg/profile).

The following is the `ps aux` command output, RSS 21056776 is the 20G residual memory I mentioned:
```
USER       PID   %CPU   %MEM    VSZ         RSS          TTY      STAT   START   TIME
root      5076   855    7.9     25883748    21056776  pts/8    Sl+       09:19  11:24
``` 
[test.pdf](https://github.com/syndtr/goleveldb/files/190922/test.pdf)

**Comment by xia0pin9** [comment]
Batch operation can improve write performance, but multiple batch inserting at the same time seems to be the reason of my problem, this may be related to the document statement that `Only one transaction can be opened at a time`.

Anyway, I configure all the workers to forward the data through a channel, and moved the batch operation from the individual workers to one goroutine. And now the memory usage is much normal.
