### ISSUE TITLE
Please create a version tag

### ISSUE THREAD

**Issue by TheTincho** [syndtr/goleveldb#140]
Hi,

Can you please tag and version this project?

I am the Debian Maintainer for goleveldb and versioning would help Debian keep up with development.

The long explanation:

Distributions like Debian and Fedora have automated tools that monitor upstream websites like GitHub to keep up with version numbers. Instead of checking your repository manually from time to time for updates, some notification mechanism will tell me that there is a new version to package. We maintain lots of packages and checking manually is not possible. Unfortunately, this infrastructure is not capable of generating version numbers just by checking the master branch.

So, if you could create versions from time to time, that'd help us loads!

Thanks.

**Comment by tandr** [comment]
vgo is coming... and it requires it.
 @syndtr Please add a tag, v1.0.0 is probably good enough for now

**Comment by terorie** [comment]
@syndtr Bump, this is the last step for full Go module support

Please run 

```
git tag v1.0.0
git push --tags
```

Thank you for merging my stuff!

**Comment by syndtr** [comment]
Done :)
