### ISSUE TITLE
How to set CompactionTableSize and WriteBuffer?

### ISSUE THREAD

**Issue by linlexing** [syndtr/goleveldb#145]
I do not understand the relationship between `CompactionTableSize`,`CompactionTotalSize`,`WriteBuffer` , and I just want to set the sst file size is 4M, how should set .

try set:
```
CompactionTableSize: 4 * opt.MiB,
CompactionTotalSize: 4 * 5 * opt.MiB,
WriteBuffer:         16 * opt.MiB,
```
but sst file size is 6M,why?

**Comment by syndtr** [comment]
Currently `CompactionTableSize` only limits tables produced by table compaction but not memdb compaction (level-0). So level-0 tables size depends on memdb size (`WriteBuffer`).

**Comment by linlexing** [comment]
Thank you very much , I understand
