### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by jacoblai** [syndtr/goleveldb#146]
only on mipsel 32bit openwrt : panic: runtime error: slice bounds out of range
linux amd64 and windows are run fine!

I'm find it golang/go#9007

look's like must change to higher go version to fix this bug???

code source:

```
func main() {
    db, err := leveldb.OpenFile("data", nil)
    if err != nil {
        fmt.Println("error:", err)
    }
    defer db.Close()

    data, err := db.Get([]byte("key"), nil)
    fmt.Println(string(data),err)

    err = db.Put([]byte("key"), []byte("value"), nil)
    data, err = db.Get([]byte("key"), nil)
    fmt.Println(string(data),err)
}
```
bug review:
1 ./main that's run allright
2 rerun ./main error show for bug view

bug view:
root@OpenWrt:/tmp# ./main
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/golang/snappy.encodeBlock(0x10410141, 0x43, 0x43, 0x1086623c, 0x1b, 0x40, 0x50)
/opt/slu/src/github.com/golang/snappy/encode_other.go:175 +0x10c4
github.com/golang/snappy.Encode(0x10410140, 0x44, 0x44, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/opt/slu/src/github.com/golang/snappy/encode.go:37 +0x370
github.com/syndtr/goleveldb/leveldb/table.(Writer).writeBlock(0x10866200, 0x1086622c, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:170 +0x1e4
github.com/syndtr/goleveldb/leveldb/table.(Writer).finishBlock(0x10866200, 0x0, 0x0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:221 +0xa0
github.com/syndtr/goleveldb/leveldb/table.(Writer).Close(0x10866200, 0x0, 0x0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/table/writer.go:294 +0x960
github.com/syndtr/goleveldb/leveldb.(tWriter).finish(0x10434740, 0x0, 0x0, 0x0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/table.go:507 +0x9c
github.com/syndtr/goleveldb/leveldb.(tOps).createFrom(0x104366e0, 0x77817d08, 0x10434700, 0x0, 0x1, 0x0, 0x0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/table.go:340 +0x288
github.com/syndtr/goleveldb/leveldb.(session).flushMemdb(0x1042e000, 0x10448070, 0x1042e080, 0x0, 0x0, 0x0, 0x0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/session_compaction.go:27 +0x1cc
github.com/syndtr/goleveldb/leveldb.(*DB).recoverJournal(0x1045a000, 0x0, 0x0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/db.go:603 +0xce0
github.com/syndtr/goleveldb/leveldb.openDB(0x1042e000, 0x0, 0x0, 0x0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/db.go:124 +0x9e8
github.com/syndtr/goleveldb/leveldb.Open(0x77817a48, 0x10434000, 0x0, 0x0, 0x0, 0x0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/db.go:196 +0x1e0
github.com/syndtr/goleveldb/leveldb.OpenFile(0x1a9b58, 0x4, 0x0, 0x0, 0x0, 0x0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/db.go:218 +0xbc
main.main()
/opt/slu/main.go:14 +0x58

goroutine 5 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x1043e0b0)
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x2a0
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
/opt/slu/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x2cc

thx!

**Comment by jacoblai** [comment]
@syndtr

**Comment by calmh** [comment]
The panic is in the `github.com/golang/snappy` package.

**Comment by jacoblai** [comment]
The first thing thanks for your reply @calmh ! this bug just view on mips's openwrt os, on ubuntu or windows os run be fine. I need more help! thx!!! a moment's ago i check leveldb file was created. i think bug just onload leveldb data or open file time error.

**Comment by syndtr** [comment]
Try updating snappy, i.e. `go get -u github.com/golang/snappy`.

**Comment by jacoblai** [comment]
thanks @syndtr ! I try to update the newer snappy error view too.  compile app I was build by [https://github.com/gomini/go-mips32.git](https://github.com/gomini/go-mips32.git) help me has a looks. that's gccgo?. thx! and I try to build tags by noasm (go build -tags=noasm main.go) target run error on the way.

**Comment by syndtr** [comment]
>  compile app I was build by https://github.com/gomini/go-mips32.git help me has a looks. that's gccgo?

The compiler is GC based, ported to mips32. You must understand that the compiler is still experimental (with that being said I can't really trust the compiler) and I don't have access to mips machine, so it would be hard for me to debug this.

>  I try to build tags by noasm (go build -tags=noasm main.go) target run error on the way.

I use  `noasm`  tag on amd64 so that it would use non-optimized go implementation instead of optimized asm version, as you can see the panic were generated by non-optimized go implementation.

For now, you may can try disabling compression, see if it's works.

**Comment by jacoblai** [comment]
@syndtr I'm disable compression, that's work!! thanks so much!

**Comment by jacoblai** [comment]
Last post remark for other person helpsful
```
o := &opt.Options{
		Compression:opt.NoCompression,
	}
	fmt.Println(o.GetCompression().String())
	db, err := leveldb.OpenFile("data", o)
	if err != nil {
		fmt.Println("error:", err)
	}
	defer db.Close()
```
