### ISSUE TITLE
Reverse iterator

### ISSUE THREAD

**Issue by pzhin** [syndtr/goleveldb#151]
If i want to get last 10 records, i have to do something like

```
iter := db.NewIterator(util.Range{}, nil)    
for ok := iter.Last(); ok && (counter < 10); ok = iter.Prev() {    
    //some code    
}    
```

Is there any other way to do this more clean and effectively?

**Comment by syndtr** [comment]
Nope, that's pretty much the only way. However, you can implements your own `comparer` that optimized for your use case.
