### ISSUE TITLE
Document how Delete behaves for an unknown key

### ISSUE THREAD

**Issue by kevinburke** [syndtr/goleveldb#154]
If I issue a Delete request for a nonexistent key, does leveldb return nil or an error message? The documentation is unclear on this point.

**Comment by syndtr** [comment]
Deleting a nonexistent key will not returns error. Delete only insert a deletion marker, this will logically remove previous key (if any) but not physically remove it, compaction will do that. Will add this to the documentation.

**Comment by syndtr** [comment]
Added 1996ac2d281f2ba6171499ac0de852e41e4d446e.
