### ISSUE TITLE
Goroutines do not increase performance

### ISSUE THREAD

**Issue by beeker1121** [syndtr/goleveldb#158]
Hi,

I'm unsure if this is an actual issue, or if this is just a side effect from how LevelDB is structured.

It seems that there is no speed increase when reading the database via multiple goroutines. I'm specifically just calling a new `Iterator` within the goroutines to read data based on key prefixes.

Here are the results from a quick test on some data.

**With** goroutines:
```
Loading database...
Done loading
Time start: 2016-11-07 23:40:44.796366138 +0000 UTC
Total: 94
Total: 114
Total: 261
Total: 1693
Total: 1781
Total: 2311
Total: 2357
Total: 2579
Total: 2915
Time end: 2016-11-07 23:40:56.571844079 +0000 UTC
Total time: 11.775478016 seconds
```

**Without** goroutines:
```
Loading database...
Done loading
Time start: 2016-11-07 23:43:38.458591384 +0000 UTC
Total: 94
Total: 114
Total: 2311
Total: 2579
Total: 2357
Total: 2915
Total: 261
Total: 1693
Total: 1781
Time end: 2016-11-07 23:43:49.349130386 +0000 UTC
Total time: 10.890539008 seconds
```

I also noticed while running the `top` command on a separate shell, that even though there's no speed increase when using goroutines, the memory used by the application does increase significantly.

Let me know if I can provide any further details to help, and thank you for your work on this!

**Comment by syndtr** [comment]
It would be much more slower since it will generates more seeks (random IO is typically slower that sequential one) and cache miss.

**Comment by beeker1121** [comment]
Another question on this, is it possible to create multiple snapshots and have those snapshots read from the database concurrently?

My main concern is how reads don't seem to be concurrent. For instance, if I'm running a web server and an endpoint reads from the database, what happens when there's 100's of requests per second? It seems that, unless snapshots can be read concurrently, each request will happen synchronously.

**Comment by syndtr** [comment]
Sure, you can create multiple snapshot, but you don't need to create snapshot to read the database concurrently. Remember, [concurrency is not parallelism](https://blog.golang.org/concurrency-is-not-parallelism).

**Comment by beeker1121** [comment]
What I mean is though, in my original post you can see that reading the database concurrently does not actually seem to do so, i.e. even using multiple goroutines to read the database, it actually performs worse than just reading from the database in a single goroutine one by one.

What I'm picturing is for instance, using the example from my original post, calling call 9 of those database reads and all 9 complete in 2915 ms (the longest single read). The way it seems to work now, is it does it one by one, so the total time for all 9 reads is 11,775 ms.

**Comment by syndtr** [comment]
Okay, let's use goroutine as example, so you want to performs calculation concurrently on let's say 4 goroutines, but you only have single CPU core, then what happen. The calculation will be scheduled on that single CPU core, it doesn't automagically become 4 times faster than when you execute the computation in sequence. Concurrency is about _dealing_ with lots of things at once, hence concurrency is not parallelism, which is _doing_ lots of things at once.

Doesn't matter if you doing it sequentially on concurrently, the data still need to be pulled from the disk, the main bottleneck here is the disk. Also, random IO is typically much slower than sequential IO, even on SSD, and reading the different parts (well, if you read from a same parts concurrently, then the chance of cache hit would be much greater, so it will be pulled from cache instead of disk, hence more performant) of database concurrently means pulling multiple files at once, which means random IO, hence much slower, also concurrency is not free, it has its own overhead.

**Comment by beeker1121** [comment]
Thank you for explaining it further, I think I understand it now. So even if you have 2 goroutines for instance reading 2 different sections of the database, if both of those reads are happening on the same logical core, then the wait is inevitable because the wait is the time it takes for the one goroutine to pull the data it needs from disk? I.e. there is no 'waiting' or 'pausing' so the other goroutine will not run until the first is complete?

Do you think this could be solved by increasing the number of CPUs and having it run in parallel?

**Comment by syndtr** [comment]
In leveldb case the bottleneck is the disk, not the CPU. So you need faster
disk.

**Comment by beeker1121** [comment]
So if better/parallel read performance is required, do you think it would be legitimate to just replicate the data onto multiple machines, and then create a sort of frontend load balancer that chooses an available machine out of the pool?

I'm using Google Compute Engine so while I could attach a Local SSD or just increase the space for higher IOPS, I'm thinking it would be cheaper to just run a bunch of smaller instances, each with just enough disk space to hold the data.

**Comment by syndtr** [comment]
Also you can try to increase the cache capacity.

**Comment by beeker1121** [comment]
Ok cool, thank you so much for your time and input on this, and especially for your work on LevelDB, I truly appreciate it!
