### ISSUE TITLE
TestDB_BulkInsertDelete sometimes fails

### ISSUE THREAD

**Issue by TheTincho** [syndtr/goleveldb#163]
Hi!

As reported in Debian bug [#834959](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834959), tests are failing around 8% of the time, due to TestDB_BulkInsertDelete panicking with:
```
	db_test.go:2826: too many uncompacted tables: 11 (7,4)
```

I guess the table compaction happens asynchronously, and so this might be related to CPU contention, but I don't know this well enough to be sure. Could somebody take a look?

Full build logs at https://people.debian.org/~sanvila/build-logs/golang-goleveldb/

Thanks!

**Comment by syndtr** [comment]
Will look into this. Thanks!

**Comment by MTecknology** [comment]
Any update?
