### ISSUE TITLE
Non-corruption guarantees

### ISSUE THREAD

**Issue by alexflint** [syndtr/goleveldb#165]
What guarantees does goleveldb make regarding database corruption? Is it possible to corrupt a database if I kill a process while it is writing?

**Comment by syndtr** [comment]
Killing process while writing should not cause corruption, in case of incomplete write, it should rolled back to previous stable state (this is default behavior, if you set `StrictAll` then incomplete write will throw error).

**Comment by Vigneshr6** [comment]
But When I take image of that running machine DB files are corrupted.

>  leveldb/storage: corrupted or incomplete meta file

**Comment by syndtr** [comment]
@Vigneshr6 thanks for pointing this out, 69e19a4 hopefully fix this.
