### ISSUE TITLE
corruption on data-block

### ISSUE THREAD

**Issue by ragros** [syndtr/goleveldb#169]
my system use this library for msg store. but now i have got a problem when writing data:
`leveldb/table: corruption on data-block (pos=13237412): checksum mismatch, want=0x3120352f got=0x81fee9 [file=000428.ldb] `

i restarted app got peace for a while.  is there anywhere to fix up even by hand? or it recovered by restart and go wrong quickly?

this is the leveldb log:
```
14:45:04.187500 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
14:45:04.250000 db@open opening
14:45:04.265625 journal@recovery F·1
14:45:04.796875 journal@recovery recovering @437
14:45:05.015625 mem@flush created L0@440 N·53 S·23KiB "729..918,v851085":"100..635,v851059"
14:45:05.046875 db@janitor F·9 G·0
14:45:05.046875 db@open done T·796.875ms
14:47:02.859375 table@compaction L0·1 -> L1·1 S·10MiB Q·851117
14:47:07.218750 table@build created L1@443 N·24337 S·10MiB "100..:98,v828878":"100..103,v835169"
14:47:07.281250 table@compaction committed F-1 S-547B Ke·0 D·0 T·4.421875s
14:47:07.281250 table@remove removed @440
14:47:07.281250 table@remove removed @439
15:54:59.984375 table@compaction L1·1 -> L2·5 S·329MiB Q·851746
15:55:02.296875 table@build error I·41905 "leveldb/table: corruption on data-block (pos=13237412): checksum mismatch, want=0x3120352f got=0x81fee9 [file=000428.ldb]"
15:55:02.296875 table@build exiting (corruption detected)
```
by hand, i found this issue in [syncthing](https://github.com/syncthing/syncthing/issues/2734),but nothing  here. I think the author many have more  reliable advice.

**Comment by syndtr** [comment]
You have two options:
* Rebuild the database using `leveldb.RecoverFile` when corruption detected, you can check wether an error is caused by corruption using `errors.IsCorrupted`
* Mask out `StrictCompaction` and `StrictReader` strict flag, so that corrupted block will be just ignored instead of throws error, i.e. `leveldb.OpenFile("path/to/db", opt.Options{Strict: opt.StrictJournalChecksum | opt.StrictBlockChecksum})`
