### ISSUE TITLE
Lock problem OSX

### ISSUE THREAD

**Issue by arielmoraes** [syndtr/goleveldb#173]
When using goleveldb in OSX the library throws lock erros at random moments. What could be causing this?

**Comment by calmh** [comment]
(Syncthing uses goleveldb extensively and I've never seen this on Mac so I expect you'll need a reproducer here.)

**Comment by arielmoraes** [comment]
Another dependency in the project was causing this, I managed to fix it by rebuilding everything, thank you for your time.
