### ISSUE TITLE
Incorrect file extension - ldb

### ISSUE THREAD

**Issue by ValleZ** [syndtr/goleveldb#176]
Native leveldb uses sst file extensions, and this implementation uses 'ldb' what doesn't allow native leveldb read database created in go.

**Comment by syndtr** [comment]
It was changed from `.sst` to `.ldb` on the original C++ implementation a while back. See https://github.com/google/leveldb/commit/0b9a89f40efdd143fa1426e7d5cd997f67ba6361.
