### ISSUE TITLE
Create a new Manifest file and Current.

### ISSUE THREAD

**Issue by ijunaid8989** [syndtr/goleveldb#185]
I had 65K of ldb files, in my leveldb directory, And 20 of them were corrupt and unrecoverable.

Also the Current and Manifest file was also corrupt, I have deleted those 20 files, along with CURRENT and Manifest file.

Is there any possibility to use this https://github.com/syndtr/goleveldb/blob/master/leveldb/session_util.go#L191 to create a new MANIFEST and Current file, with existing recoverable LDB files?

**Comment by syndtr** [comment]
Yep, that's what `leveldb.RecoverFile` for.

**Comment by ijunaid8989** [comment]
Okay thanks,

Btw, Its necessary to have the 'dir.log' file to be present while
recovering the db?



Junaid Farooq

On 24 November 2017 at 11:28, Suryandaru Triandana <notifications@github.com
