### ISSUE TITLE
how to use raw block device for db

### ISSUE THREAD

**Issue by vtolstov** [syndtr/goleveldb#187]
I want to eliminate fs layer and read/write to block device, how can i do that? Does already somebody create raw block device storage interface implementation?

**Comment by bradfitz** [comment]
Sorry, this is not possible. Or, it would be a lot of work for nearly no benefit. If anything, LevelDB could be modified to use a provided a VFS interface implementation, but storing on a block device doesn't really make sense.

**Comment by vtolstov** [comment]
Thanks
