### ISSUE TITLE
clear space need restart service

### ISSUE THREAD

**Issue by ragros** [syndtr/goleveldb#196]
we use this in windows as data server,once the disk space is full.we should restart service.and I found the error state has no chance clear after free disk space . 
```
github.com/syndtr/goleveldb/leveldb/journal/journal.go

@@ -81,6 +81,8 @@
 	"encoding/binary"
 	"fmt"
 	"io"
+	"os"
+	"strings"
 
 	"github.com/syndtr/goleveldb/leveldb/errors"
 	"github.com/syndtr/goleveldb/leveldb/storage"
@@ -435,6 +437,12 @@
 	w.seq++
 	w.writePending()
 	if w.err != nil {
+		//the message is: There is not enough space on the disk.
+		if pathErr, ok := w.err.(*os.PathError); ok &&
+			strings.Contains(pathErr.Error(), "space") {
+			w.err = nil
+			return pathErr
+		}
 		return w.err
 	}
 	if w.f != nil {
```
   this  is my solution . but the space error did match any code(ambiguity in syscall ) ,so it is not  elegant.
   anywhere I think the offical source should resolve it.

**Comment by disksing** [comment]
Hi, I also encountered this problem.
It seems to be related to the implementation of `journal.Writer`. When `journal.Writer` encounters an error, it will save the error in the `err` member variable and will never be cleared. At the same time, it can be seen in `db_state` that `journal.Writer` will [not be reset after creation](https://github.com/syndtr/goleveldb/blob/758128399b1df3a87e92df6c26c1d2063da8fabe/leveldb/db_state.go#L137-L143), so it will [always report an error](https://github.com/syndtr/goleveldb/blob/758128399b1df3a87e92df6c26c1d2063da8fabe/leveldb/journal/journal.go#L470-L472).

**Comment by syndtr** [comment]
This is by design. The database will enter into read-only mode when encounter file-system level write failure. It is a circuit breaker so that it won't messed up your data consistency.
You need to reopen the database to be able to write again. You can implement this logic in your app, or let your service to exit and let the service manager restart the service or something.
