### ISSUE TITLE
what is the difference between Option.NoSync and  WriteOptions.Sync ?

### ISSUE THREAD

**Issue by laizy** [syndtr/goleveldb#199]
is option.NoSync a global setting?
when it is used in function DB.Open, DB.OpenFile,..etc, then DB.Put, DB.Delete, DB.Write will use that as default value if WriteOptions is not provided?

**Comment by syndtr** [comment]
> is option.NoSync a global setting?

Not really, it just fsync "kill switch".

There's no global settings for `WriteOptions.Sync`. However, if you set `Options.NoSync = true` it will override `WriteOptions.Sync` and disable write sync.
