### ISSUE TITLE
shortenb  index out of range

### ISSUE THREAD

**Issue by hstcscolor** [syndtr/goleveldb#213]
when i = 4,  out of range

func shortenb(bytes int) string {
	i := 0
	for ; bytes > 1024 && i < 4; i++ {
		bytes /= 1024
	}
	return fmt.Sprintf("%d%sB", bytes, bunits[i])
}

**Comment by syndtr** [comment]
Fixed ae970a0732be3a1f5311da86118d37b9f4bd2a5a
