### ISSUE TITLE
why do you  rewrite leveldb with golang?

### ISSUE THREAD

**Issue by gradient-zero** [syndtr/goleveldb#219]
why do you  rewrite leveldb with golang?

**Comment by syndtr** [comment]
why not?

**Comment by gradient-zero** [comment]
any benefits? such as more concurrency, multi-process, client-server Architecture, etc.

**Comment by syndtr** [comment]
Well, back then (circa 2012-2013) I need an embedded on-disk key/value database than native to Go (I don't want to use CGO) that can handle decent amount of data and there wasn't any, so I decided to rewrite leveldb in Go as inventing an entirely new database format wasn't option for me back then.

**Comment by gradient-zero** [comment]
Thanks, I got it.
