### ISSUE TITLE
Compaction time can be quite big

### ISSUE THREAD

**Issue by melekes** [syndtr/goleveldb#226]
Hey! I am investigation the performance decline in our software https://github.com/tendermint/tendermint/issues/1835. We're using goleveldb as a primary DB for storing blocks plus some other data.

Looks like saving a batch of data (~1MB) can result in ~ 15 sec. due to compaction process or something:

https://github.com/tendermint/tendermint/issues/1835#issuecomment-402054099
(the time seems to be increasing with every spike)

The write speed is approximately 1MB per second.

Is this expected and we need to fine tune compaction options or this looks like a bug to you?

Thank you!

**Comment by ackratos** [comment]
do we have any findings or suggestions on tuning options here?

**Comment by melekes** [comment]
@ackratos have you tried cleveldb? compaction times are much lower there

**Comment by ackratos** [comment]
> @ackratos have you tried cleveldb? compaction times are much lower there

We have tried cleveldb, we don't do block indexing much (we only index on default tx hash to txindex db...) We tested 100 million account in application.db, memory leak happens (we build latest goleveldb and levigo release but didn't apply this fix yet https://github.com/cosmos/cosmos-sdk/issues/3842) and very crazy (26G/32G are used...). So no chance to hit compaction issue yet.

We decide stop trying cleveldb in short term and focus on tuning goleveldb, after tracing how compaction is triggered, I have a naive idea that delayed compaction with this parameter `CompactionTotalSizeMultiplier: 15`:

```
var defaultOptions = &opt.Options{OpenFilesCacheCapacity: 1024,
	BlockCacheCapacity: 768 / 2 * opt.MiB,
	WriteBuffer:        768 / 4 * opt.MiB, // Two of these are used internally
	Filter:             filter.NewBloomFilter(10),
	CompactionTotalSizeMultiplier: 15,
}
```

Should have some result tomorrow.

**Comment by syndtr** [comment]
You might want to try latest master branch, there're series of PR by @rjl493456442 that has been merged recently that improves compaction performance. See #264, #267, #268 and #270.

**Comment by nullne** [comment]
@syndtr  i met the same problem. the put latency increase high every rough 10 minutes.  i am build the project will the latest `goleveldb`. hope this works

**Comment by rjl493456442** [comment]
@nullne 10 milliseconds?

**Comment by nullne** [comment]
@rjl493456442  yes, with 40-byte key and 200-byte value. except the spike the response time is quite  low

**Comment by rjl493456442** [comment]
@nullne From the go-ethereum aspect, we monitor the archive syncing procedure and this shows with the latest master branch, the `write_delay` is gone. It means no write operation is stuck anymore.

The average disk writing speed of geth node is 100 MB/s.

But it is possible that if your write load is super heavy, the compaction speed is definitely slower than the write speed, then a part of write operations will be delayed. It can be the cause of the spikes.

**Comment by nullne** [comment]
@rjl493456442 thanks for your time 
do you think  that our write load is super heavy? is there anything to config to reduce the spikes? i have built the project and test the performance now, it takes time to see the difference if there is

**Comment by rjl493456442** [comment]
@nullne You mean if there is no read, then the write spike is not obvious?

**Comment by nullne** [comment]
@rjl493456442  yes 
![Image](https://user-images.githubusercontent.com/6008447/56653533-6bcf1c00-66c0-11e9-920c-c9220dbaa0f0.png)

**Comment by nullne** [comment]
i tried `rocksdb` and c `leveldb`.  finally we decided to use `rocksdb` via `cgo`

**Comment by melekes** [comment]
Tested Tendermint with the latest master (5c35d600f0ca). Compaction times are much lower now ~ 2-3s. Thanks! I think this can be closed now.

**Comment by 0zAND1z** [comment]
Does this mean that Tendermint can handle heavy load reasonably well?

The paragraph under [Database](https://docs.tendermint.com/master/tendermint-core/running-in-production.html#database) sectoin of Tendermint Core docs mentions this PR. Should someone update that para?

**Comment by melekes** [comment]
> @melekes, Does this mean that Tendermint can handle heavy load reasonably well?

I'm currently investigating long pauses, which happen every now and then https://github.com/tendermint/tendermint/issues/3905#issuecomment-681854328. As I said, compaction is no longer an issue.

> The paragraph under [Database](https://docs.tendermint.com/master/tendermint-core/running-in-production.html#database) sectoin of Tendermint Core docs mentions this PR. Should someone update that para?

good catch 👍 will do
