### ISSUE TITLE
Shared cache?

### ISSUE THREAD

**Issue by gaillard** [syndtr/goleveldb#228]
Looks like GetBlockCacher isn't called anywhere?
In fact it looks like the only thing used from the options passed to *DB is the cache capacity https://github.com/syndtr/goleveldb/blob/master/leveldb/table.go#L454 which it uses and directly creates an LRU.

I'm interested in passing in a cache.NewLRU to more than one database that is larger than it could be if each had their own. Because of the namespace that the cache supports already and seems to use file descriptor number, it should be safe correct?

**Comment by syndtr** [comment]
> I'm interested in passing in a cache.NewLRU to more than one database that is larger than it could be if each had their own. Because of the namespace that the cache supports already and seems to use file descriptor number, it should be safe correct?

You can't share LRU instance to multiple database instance as the namespace will clash, the file descriptor number which used as namespace ID is unique only to that particular DB instance (i.e, not globally). However, with some changes to "LRU cacher" you can do that, you just need a way to logically partition those namespace.

**Comment by gaillard** [comment]
Ok thanks for the info, I'll take a look at the internals to see how it works to segment it out. You're right, I was assuming unix fd which I should not have :)

**Comment by gaillard** [comment]
Correct me if I am missing something.

 0. In order to share a cache since the map part of the cache is done in cache.Cache and the recency (lru) part done in cache.Cacher, the existing line `bcache = cache.NewCache(bcacher)` in creation of `*tOps` will need to pull a `cache.Cache` from options.

In addition to that it seems the options are:
1. Change the storage pkg to use fs descriptor (only when on linux). Comes with the cost that it will change what is written for disk paths, and not localized to the cache. Plus I think the nums are used for some kind of ordering?
2. "Prefix" the `*tOps.f.fd.Num` in `*tOps` methods when passed to `cache.Cache` (`Get()`,`EvictNS()` etc), for example just a unique upper byte. That "prefix" perhaps given in options?
3. Instead of #0 pulling `cache.Cache` from options, it can pull a new interface from options that matches `cache.Cache`. That way the main program put on a different "prefixing" (similar to #2) wrapper for each db instance?

Any other simpler options? If not I think I'll proceed down #2 as it seems simplest. I'd like to contribute it back so if you have any preference please let me know :)

**Comment by syndtr** [comment]
> Change the storage pkg to use fs descriptor (only when on linux). Comes with the cost that it will change what is written for disk paths, and not localized to the cache. Plus I think the nums are used for some kind of ordering?

This is a no go. The nums are used to identify files on-disk and stored in on-disk metadata, it is some kind of filename.

> "Prefix" the *tOps.f.fd.Num in *tOps methods when passed to cache.Cache (Get(),EvictNS() etc), for example just a unique upper byte. That "prefix" perhaps given in options?

You can simply wraps `cache.LRU` or creates your own `cache.Cacher` implementation if you want.

Anyway, `cache.Cache` only wraps `cache.Cacher` and act as some kind of concurrency control, i.e so it will not pull same data at the same time, do some preliminary caching, etc.

**Comment by gaillard** [comment]
@syndtr I must be missing something then. Isn't `cache.Cache` the hashtable portion of a normal lru implementation (usually using a linked list plus hashtable) and `cache.lru` the linked list part? There isn't a way to Get for example from `cache.lru` only promote/evict.

So just sharing my own or wrapped `cache.Cacher` will certainly help what is considered recent be common, which would be a big benefit with lots of db instances. I'll test and report :)
