### ISSUE TITLE
Nil defererence within NewIterator

### ISSUE THREAD

**Issue by holiman** [syndtr/goleveldb#235]
We hit upon this within our travis ci, due to some test which probably triggers some race condition. Nevertheless, the [getMems](https://github.com/syndtr/goleveldb/blob/master/leveldb/db_state.go#L158) function obviously expects that `db.mem` and `db.frozenMem` can be nil: 

```golang
func (db *DB) getMems() (e, f *memDB) {
	db.memMu.RLock()
	defer db.memMu.RUnlock()
	if db.mem != nil {
		db.mem.incref()
	} else if !db.isClosed() {
		panic("nil effective mem")
	}
	if db.frozenMem != nil {
		db.frozenMem.incref()
	}
	return db.mem, db.frozenMem
}
```
The [`newRawIterator`](https://github.com/syndtr/goleveldb/blob/master/leveldb/db_iter.go#L38), however, expects at least the first value to be non-nil: 
```
	em, fm := db.getMems()
        ...// abbreviated
	emi := em.NewIterator(slice)
```

**Comment by syndtr** [comment]
Did the database closed or in the process of closing? getMems should [raise "nil effective mem" panic](https://github.com/syndtr/goleveldb/blob/master/leveldb/db_state.go#L164) if database is not closed.

**Comment by fjl** [comment]
My guess: `NewIterator` checks whether the database is closed and proceeds if it's open. If the DB is closed while `NewIterator` executes and `db.mem` is set to nil before iterator creation hits `newRawIterator`,  it can trigger this crash. `Close` would need to wait for all `NewIterator` calls before proceeding to fix this.

**Comment by syndtr** [comment]
I'm intentionally make `Close` not that strongly consistent to avoid using mutex. I think user should just stop doing anything on the database before deciding to call `Close`?

Hence the warning:
> // It is not safe to close a DB until all outstanding iterators are released.
> // It is valid to call Close multiple times. Other methods should not be
> // called after the DB has been closed.

**Comment by fjl** [comment]
We have fixed this in our codebase through tighter synchronizatin, ensuring that iterator creation can't happen concurrently with `Close`.
