### ISSUE TITLE
Iterate [][]byte bug

### ISSUE THREAD

**Issue by Kojans** [syndtr/goleveldb#236]
func GetAllbyValue(db *leveldb.DB, value []byte) [][]byte {
		var ans [][]byte

		iter := db.NewIterator(nil, nil)
		for iter.Next() {
			fmt.Println(ans)
			if bytes.Equal(iter.Value(), db) {
				key := iter.Key()
				ans = append(ans, key)
			}
		}
		iter.Release()
		err := iter.Error()
		if err != nil {
			panic(err)
		}
		return ans
	}
It returns last key

**Comment by Kojans** [comment]
> The Key() method documentation says the returned value is only valid until you seek the iterator (i.e., call Next()). You need to copy the value if you want to retain it longer than that.

`append(ans, key)`
isn'tit copy?

**Comment by calmh** [comment]
No. https://blog.golang.org/go-slices-usage-and-internals

**Comment by Kojans** [comment]
oh, Sorry
