### ISSUE TITLE
EvictNS performance

### ISSUE THREAD

**Issue by holiman** [syndtr/goleveldb#245]
Hi, 
I did some profiling of [go-ethereum](https://github.com/ethereum/go-ethereum) yesterday (unfortunately I don't have the graphs on this machine). During a full block import, when it's busy crunching through blocks as, it turned out that one of the main timesinks was [`EvictNS`](https://github.com/syndtr/goleveldb/blob/0d5a0ceb10cf9ab89fdd744cc8c50a83134f6697/leveldb/cache/lru.go#L151)

Doing some further investigation, I could see that it often would call `EvictNS` hundreds of times, in a sequence with different `ns` namespaces. Each such invocation would iterate through a linked list of ~10K items. 

1. I'm wondering if this interpretation correct: The lru cache keeps tab on data from various database-files, and tags pieces of data with the file descriptor as `namespace`. Whenever the database wants to close a file, it tells the cache to forcably evict all the data-items that are associated with the file in question? 

2. If the `EvictNS` is turned into a no-op, which I tested, I did not hit upon any obvious errors. So I wonder if there are any possible data corruptions/races etc that could happen due to _not_ evicting the data (and instead simply rely on the lru cache to organically evict it in due time). 

3. If 2) is not 'safe', I saw that there are a couple of other options for eviction that could be used. One would be to collect eviction ids during `EvictNS`, and then call `EvictNSFinalize` after all deletions have been performed, to evict multiple namespaces on the same iteration. 

4. I'm also wondering if it wouldn't be better to use a different LRU with more direct namespace support, to evict namespaces without all the iteration. Or maybe there are some other configuration options that we should look into?

**Comment by syndtr** [comment]
1. Yes that's correct, the idea is to get rid of removed files caches as it no longer needed. Unfortunately the performance implication escape me when I'm implementing this, nice finding btw :) 
2. Yes, making `EvictNS` no-op is safe actually
4. I agree, I think maps is good enough for this and add options to disable this, or probably remove  `EvictNS` altogether

**Comment by holiman** [comment]
Great to hear! I dug up the graph and added it here, in case you are interested:https://github.com/ethereum/go-ethereum/issues/18181

**Comment by syndtr** [comment]
@holiman Thanks!

`EvictNS` now disabled by default.
