### ISSUE TITLE
Read key only in NewIterator

### ISSUE THREAD

**Issue by vitalvas** [syndtr/goleveldb#252]
Hello,

How to read key only in "NewIterator" function?

For now(as far as I can see) in NewIterator - reading key and value.

I have a DB size of more than 1TB. Key avg size - 128 bytes and value avg size 120 kbytes.
And read with Seek - very slow.

I think, read key only - will increase performance and reduce the amount of disk IO.

**Comment by syndtr** [comment]
No, that not possible. On-disk key and values are encoded in series and leveldb operates in blocks, since blocks contains both key and value it is not possible read just the keys.
However, you can implement some kind of indexing  if you want fast access for your keys.
