### ISSUE TITLE
Q: best way to move data between keys

### ISSUE THREAD

**Issue by tandr** [syndtr/goleveldb#253]
Hello
If I have a block of data attached to a key, but now I need to move it to a different key, is there a "cheap" way to do it ?

For example if I have simple key-value of (file name -> 100 meg of content), and I rename a file to something, is there a cheap way to change it without removing "100 meg of content" and then re-adding it again?

**Comment by syndtr** [comment]
No. That's pretty much the only possibility way. This is limitation of LSM-tree based database like leveldb, and there are no workaround it.
