### ISSUE TITLE
Improve docs for iterator buffer reuse 

### ISSUE THREAD

**Issue by fernandoabolafio** [syndtr/goleveldb#258]
I noticed that iterator.Value() may reuse the same buffer leading to unexpected results.
For instance I had this code:
```Go
        iter := l.userdb.NewIterator(nil, nil)
	for iter.Next() {
		key := iter.Key()
		value := iter.Value()
		snapshot.Snapshot[string(key)] = value
		fmt.Printf("%v ->>>> %+v \n", string(key), string(value))
	}
	iter.Release()

	for k, v := range snapshot.Snapshot {
		fmt.Printf("%v ->>>> %+v \n", k, string(v))
	}
```
The result of the first print showed me the correct values for each item from the database:
```
user  ->>>> {"RecordType":1,"RecordVersion":1,"ID":"04569e7e-3c25-4cae-86fc-e94b0e2481c3","Email":"do@lores.com","Username":"dolores"}
lastpaywallindex ->>>> {"recordtype":3,"recordversion":1,"index":1}
```

However, after building the map and iterating it to see what was in there, I got this:
```
lastpaywallindex ->>>> {"recordtype":3,"recordversion":1,"index":1}
user ->>>>{"recordtype":3,"recordversion":1,"index":1}9e7e-3c25-4cae-86fc-e94b0e2481c3" ,"Email":"do@lores.com","Username":"dolores" }
```
See how the value under user is messed up, that happened due buffer user. 
After spending some time on it I found that the solution was to do this:
```Go

origValue := iter.Value()
value := make([]byte, len(origValue))
copy(value, origValue)
```
I think would be helpful to update the docs to alert other devs about this.

**Comment by syndtr** [comment]
Actually this already documented in the [iterator.Itearator interface](https://godoc.org/github.com/syndtr/goleveldb/leveldb/iterator#Iterator).
However, I agree with you, warning should be added to more obvious place like `NewIterator` method for example.
