### ISSUE TITLE
Consider adding semantic version tags to the repository

### ISSUE THREAD

**Issue by creachadair** [syndtr/goleveldb#259]
This package has a `go.mod` file, but there are currently no release tags. For better integration with Go modules, would you be willing to start tagging versions? Even just running `git tag v0.0.1 master ; git push origin v0.0.1` would be sufficient to get the tag history started, without committing you to any API promises.

**Comment by creachadair** [comment]
Ping @syndtr, do you have any concerns about adding version tags? Thanks!

**Comment by syndtr** [comment]
Done :)

**Comment by creachadair** [comment]
Thank you!
