### ISSUE TITLE
Self dependent batch write

### ISSUE THREAD

**Issue by kprimice** [syndtr/goleveldb#266]
Is it possible to `Get` a key that has just been added to a batch?

```go
batch := new(leveldb.Batch)
// ...
batch.Put(key1, data1)
// ...
db.Get(key1, nil)
// ...
err = db.Write(batch, nil)
```

This naive code does not work because `key1` is not found

**Comment by syndtr** [comment]
Nope. Batch is kind of bucket where you can collect entries to be inserted into database in batch. So it's not in database yet.
