### ISSUE TITLE
why is 116

### ISSUE THREAD

**Issue by yj511608130** [syndtr/goleveldb#278]
why here is 116
[bench_test](https://github.com/syndtr/goleveldb/blob/c3a204f8e96543bb0cc090385c001078f184fc46/leveldb/bench_test.go#L191)
100(range)*(16(key)+(16)value+8) = 4000bytes

**Comment by syndtr** [comment]
It is bytes per operation:

> SetBytes records the number of bytes processed in a single operation. If this is called, the benchmark will report ns/op and MB/s.

```
		p.keys[i], p.values[i] = []byte(fmt.Sprintf("%016d", i)), v.get(100)
```
The key is 16 bytes and the value is 100 bytes. We don't take overhead into consideration.
