### ISSUE TITLE
confusing variable name

### ISSUE THREAD

**Issue by ping40** [syndtr/goleveldb#279]
in line 750, variable  x is a confusing name, changing  to err  is more readable.
 

```


        func (db *DB) mCompaction() {
	var x cCmd

	defer func() {
line 750		if x := recover(); x != nil {      ---> variable  x is a confusing name
			if x != errCompactionTransactExiting {  
				panic(x)
			}
		}
		if x != nil {
			x.ack(ErrClosed)
		}
		db.closeW.Done()
	}()

```

**Comment by tv42** [comment]
Nothing requires panic to be called with an `error`. The type of `x` is `interface{}`, and it's underlying type is whatever it happens to be. https://play.golang.org/p/HJAHDw-TXOl
