### ISSUE TITLE
Transaction commit/discard & iterator clarification

### ISSUE THREAD

**Issue by calmh** [syndtr/goleveldb#287]
Hi! The documentation on allowed sequence of calls around transactions and iterators is a bit unclear to me. I would like stuff like the following code to be valid with respect to the defers:

```go
func deleteAll(db *leveldb.DB) error {
    tran, err := db.OpenTransaction()
    if err != nil {
        return err
    }
    defer tran.Discard()

    it := tran.NewIterator(...)
    defer it.Release()

    for it.Next() {
        if err := tran.Delete(it.Key(), nil); err != nil {
            return err
        }
    }
    if err := it.Error(); err != nil {
        return err
    }
    return tran.Commit()
}
```

Specifically,

- The deferred `Discard` can be called even if `Commit` has succeeded?
- The iterator can be `Release`d after `Commit`?

Otherwise ordering all of this manually becomes a bit of busy work around all transactions.

**Comment by syndtr** [comment]
Those use of defers should be fine regardless of using 3fca957 or not (since the defer would call iterator `Release` first before `Discard`).
