### ISSUE TITLE
OpenFile returns error when opening a locked database in read-only mode.

### ISSUE THREAD

**Issue by cedws** [syndtr/goleveldb#306]
This seems to be related to #111, but I don't think any fix was upstreamed.

### Expected behaviour
Since I am opening the database in `ReadOnly` mode, I would expect that a lock doesn't need to be acquired since nothing should be written. However, I'm not sure if this is how it works in LevelDB.

### Actual behaviour
When calling `OpenFile` on a locked database (`LOCK` file present), with the `ReadOnly` database option set to `true`, the database will fail to open. On Windows, I'm getting:

```
The process cannot access the file because it is being used by another process.
```

**Comment by cedws** [comment]
I've discovered that opening a locked database in read-only mode on Linux actually works fine. There's actually a test for this behaviour which passes on Linux but fails when ran on Windows, so the bug is Windows-specific.

**Comment by ShadiestGoat** [comment]
Why was this issue closed? It is still present from my testing?

**Comment by cedws** [comment]
Can you post some debugging? This fix worked for my situation so let's work out what the difference is.

**Comment by ShadiestGoat** [comment]
> Can you post some debugging? This fix worked for my situation so let's work out what the difference is.

What exactly do you need? I'm not sure what to debug here haha?
