### ISSUE TITLE
how can i DestroyDb

### ISSUE THREAD

**Issue by 516108736** [syndtr/goleveldb#313]
i want to removes a database entirely, removing everything from the filesystem.

who can tell me what i should do 

thanks

**Comment by 516108736** [comment]
https://github.com/facebook/rocksdb/blob/6477075f2c21f37c4abe57dafa6d0eab9ee469b3/include/rocksdb/db.h#L1496

**Comment by syndtr** [comment]
Just close the DB (if still open) and remove the file (.i.e using `os.RemoveAll`).
