### ISSUE TITLE
disable auto compaction

### ISSUE THREAD

**Issue by dajohi** [syndtr/goleveldb#36]
Is there a way to disable the auto db compaction goleveldb does?  My db keeps being corrupted, and if it does panic, it is always in db_compaction.go

I want to test filling my DB without goleveldb running compaction at all to see if it still corrupts.

**Comment by fghanadi** [comment]
I have a problem in using leveldb. I'm using leveldb for indexing books and words in a library program but when size of the library become huge (like 3000) adding a book gets too much time. when profiling my program I undarestand that leveldb compaction gets a big part of time. Is there a way to defer compaction to the end of the program or anything else to solve this problem?
thanks in advance
