### ISSUE TITLE
Is this dead code?

### ISSUE THREAD

**Issue by Alex-duzhichao** [syndtr/goleveldb#360]
```go
// Rotate memdb if it's reach the threshold.
if batch.internalLen >= mdbFree {
	db.rotateMem(0, false)
}
```
The snippet code above is at [L248](https://github.com/syndtr/goleveldb/blob/master/leveldb/db_write.go#L248)  in db_write.go. I think the condition would never be true because the returned value `mdbFree` of `db.flush` at [L154](https://github.com/syndtr/goleveldb/blob/master/leveldb/db_write.go#L154) is guaranted to be larger than `batch.internalLen`.

So is the snippet above a dead code?

Thanks

**Comment by syndtr** [comment]
There are the case were `batch.internalLen == mdbFree`, the *greater than*
is just for good measure.

**Comment by syndtr** [comment]
Also `mdbFree` is not a hard limit, so actually `batch.internalLen` can be
greater than `mdbFree` because of batch merging.

**Comment by Alex-duzhichao** [comment]
Yes, get it. 
Thank you so much.
