### ISSUE TITLE
Restart goleveldb takes long time to run

### ISSUE THREAD

**Issue by Alex-duzhichao** [syndtr/goleveldb#378]
We have a long-lived application using goleveldb in our production environment. After several months running, the space occupied by leveldb is about 400+GB, and the `MANIFEST` file occupies about 20+GB. During restart this application, I notice that recovery of the `MANIFEST` file takes several minutes to run. In my opinion,  the `MANIFEST` file records the log of compaction. So should goleveldb take snapshots for the `MANIFEST` file periodically to reduce the restart time ?
Thanks very much!

**Comment by LuciferMS** [comment]
This is still an interesting question, that is how many files were deleted by leveldb during compaction. How many files were added will be recorded inside the version control, update the version status, and then if the database is closed, the database will be restored by the version information. This way there is a problem that when the database has a large amount of data and has been running for a long time, the version log file will be very large, resulting in a long time to restart the database. My idea is to add database parameters, the version file to a certain degree of size, I use the current state to generate version information, delete the original version file, effectively prevent the version file expansion.

**Comment by Alex-duzhichao** [comment]
> 

Yes, in this [PR](https://github.com/syndtr/goleveldb/pull/380), I add an option to limit the maximum size of the MANIFEST file.

**Comment by elliotchenzichang** [comment]
I've read your code, and I think your logic is right. But one thing I don't understand is why you have added a new dependency library for testing.
`github.com/stretchr/testify v1.7.0`
I think using the original test dependency library should achieve the desired test results.

**Comment by LuciferMS** [comment]
> > This is still an interesting question, that is how many files were deleted by leveldb during compaction. How many files were added will be recorded inside the version control, update the version status, and then if the database is closed, the database will be restored by the version information. This way there is a problem that when the database has a large amount of data and has been running for a long time, the version log file will be very large, resulting in a long time to restart the database. My idea is to add database parameters, the version file to a certain degree of size, I use the current state to generate version information, delete the original version file, effectively prevent the version file expansion.
> 
> > 
> 
> Yes, in this [PR](https://github.com/syndtr/goleveldb/pull/380), I add an option to limit the maximum size of the MANIFEST file.

I've read your code, and I think your logic is right. But one thing I don't understand is why you have added a new dependency library for testing.
github.com/stretchr/testify v1.7.0
I think using the original test dependency library should achieve the desired test results.

**Comment by Alex-duzhichao** [comment]
> > > This is still an interesting question, that is how many files were deleted by leveldb during compaction. How many files were added will be recorded inside the version control, update the version status, and then if the database is closed, the database will be restored by the version information. This way there is a problem that when the database has a large amount of data and has been running for a long time, the version log file will be very large, resulting in a long time to restart the database. My idea is to add database parameters, the version file to a certain degree of size, I use the current state to generate version information, delete the original version file, effectively prevent the version file expansion.
> > 
> > 
> > > 
> > 
> > 
> > Yes, in this [PR](https://github.com/syndtr/goleveldb/pull/380), I add an option to limit the maximum size of the MANIFEST file.
> 
> I've read your code, and I think your logic is right. But one thing I don't understand is why you have added a new dependency library for testing. github.com/stretchr/testify v1.7.0 I think using the original test dependency library should achieve the desired test results.

The reason I introduce `github.com/stretchr/testify` is that I think testing code can be more terse  than using `testing`.
For example:
`github.com/stretchr/testify`
```golang
import "github.com/stretchr/testify/require"

require.NoError(t, err)
```
vs

`testing`
```golang
import "testing"

if err != nil {
    t.Fatalf()
}

```

**Comment by LuciferMS** [comment]
> > > > This is still an interesting question, that is how many files were deleted by leveldb during compaction. How many files were added will be recorded inside the version control, update the version status, and then if the database is closed, the database will be restored by the version information. This way there is a problem that when the database has a large amount of data and has been running for a long time, the version log file will be very large, resulting in a long time to restart the database. My idea is to add database parameters, the version file to a certain degree of size, I use the current state to generate version information, delete the original version file, effectively prevent the version file expansion.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > Yes, in this [PR](https://github.com/syndtr/goleveldb/pull/380), I add an option to limit the maximum size of the MANIFEST file.
> > 
> > 
> > I've read your code, and I think your logic is right. But one thing I don't understand is why you have added a new dependency library for testing. github.com/stretchr/testify v1.7.0 I think using the original test dependency library should achieve the desired test results.
> 
> The reason I introduce `github.com/stretchr/testify` is that I think testing code can be more terse than using `testing`. For example: `github.com/stretchr/testify`
> 
> ```go
> import "github.com/stretchr/testify/require"
> 
> require.NoError(t, err)
> ```
> 
> vs
> 
> `testing`
> 
> ```go
> import "testing"
> 
> if err != nil {
>     t.Fatalf()
> }
> ```

But I feel that fixing bugs and adding a new test dependency library are two different things. I think you can raise a separate PR to add a new test dependency library. I also feel that if you want to replace it with your recommended dependency library, it is best to use one standard for all testing methods. Otherwise it would be strange to have two sets of standards in one set of code.

**Comment by Alex-duzhichao** [comment]
> 

Well，I think it's not all-or-nothing. 
In lots of popular golang projects (e.g., kubenetes, etcd and gin), they use `testify` and `testing` both together.

**Comment by Alex-duzhichao** [comment]
> > 
> 
> Well，I think it's not all-or-nothing. In lots of popular golang projects (e.g., kubenetes, etcd and gin), they use `testify` and `testing` both together.

**Comment by Alex-duzhichao** [comment]
> > > > > This is still an interesting question, that is how many files were deleted by leveldb during compaction. How many files were added will be recorded inside the version control, update the version status, and then if the database is closed, the database will be restored by the version information. This way there is a problem that when the database has a large amount of data and has been running for a long time, the version log file will be very large, resulting in a long time to restart the database. My idea is to add database parameters, the version file to a certain degree of size, I use the current state to generate version information, delete the original version file, effectively prevent the version file expansion.
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > Yes, in this [PR](https://github.com/syndtr/goleveldb/pull/380), I add an option to limit the maximum size of the MANIFEST file.
> > > 
> > > 
> > > I've read your code, and I think your logic is right. But one thing I don't understand is why you have added a new dependency library for testing. github.com/stretchr/testify v1.7.0 I think using the original test dependency library should achieve the desired test results.
> > 
> > 
> > The reason I introduce `github.com/stretchr/testify` is that I think testing code can be more terse than using `testing`. For example: `github.com/stretchr/testify`
> > ```go
> > import "github.com/stretchr/testify/require"
> > 
> > require.NoError(t, err)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > vs
> > `testing`
> > ```go
> > import "testing"
> > 
> > if err != nil {
> >     t.Fatalf()
> > }
> > ```
> 
> But I feel that fixing bugs and adding a new test dependency library are two different things. I think you can raise a separate PR to add a new test dependency library. I also feel that if you want to replace it with your recommended dependency library, it is best to use one standard for all testing methods. Otherwise it would be strange to have two sets of standards in one set of code.

Well，I think it's not all-or-nothing.
In lots of popular golang projects (e.g., kubenetes, etcd and gin), they use testify and testing both together.

**Comment by LuciferMS** [comment]
> > > > > > This is still an interesting question, that is how many files were deleted by leveldb during compaction. How many files were added will be recorded inside the version control, update the version status, and then if the database is closed, the database will be restored by the version information. This way there is a problem that when the database has a large amount of data and has been running for a long time, the version log file will be very large, resulting in a long time to restart the database. My idea is to add database parameters, the version file to a certain degree of size, I use the current state to generate version information, delete the original version file, effectively prevent the version file expansion.
> > > > > 
> > > > > 
> > > > > > 
> > > > > 
> > > > > 
> > > > > Yes, in this [PR](https://github.com/syndtr/goleveldb/pull/380), I add an option to limit the maximum size of the MANIFEST file.
> > > > 
> > > > 
> > > > I've read your code, and I think your logic is right. But one thing I don't understand is why you have added a new dependency library for testing. github.com/stretchr/testify v1.7.0 I think using the original test dependency library should achieve the desired test results.
> > > 
> > > 
> > > The reason I introduce `github.com/stretchr/testify` is that I think testing code can be more terse than using `testing`. For example: `github.com/stretchr/testify`
> > > ```go
> > > import "github.com/stretchr/testify/require"
> > > 
> > > require.NoError(t, err)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > vs
> > > `testing`
> > > ```go
> > > import "testing"
> > > 
> > > if err != nil {
> > >     t.Fatalf()
> > > }
> > > ```
> > 
> > 
> > But I feel that fixing bugs and adding a new test dependency library are two different things. I think you can raise a separate PR to add a new test dependency library. I also feel that if you want to replace it with your recommended dependency library, it is best to use one standard for all testing methods. Otherwise it would be strange to have two sets of standards in one set of code.
> 
> Well，I think it's not all-or-nothing. In lots of popular golang projects (e.g., kubenetes, etcd and gin), they use testify and testing both together.

Sorry brother, this is just my personal opinion. Don't take it to heart.
