### ISSUE TITLE
Is it possible to read the db from to different programs?

### ISSUE THREAD

**Issue by rew1nter** [syndtr/goleveldb#432]
I got `resource temporarily unavailable` error while trying this

**Comment by berkantay** [comment]
Did you mean read at the same time while you write to db? @rew1nter

**Comment by rew1nter** [comment]
Yes

**Comment by berkantay** [comment]
If that's the case you should have a lock mechanism or interprocess communication to release ownerhip of the file(database) I believe. Other choice would be write a service on top of leveldb to execute queries on top of it. Then you can call it's functions wherever you want.
