### ISSUE TITLE
Clarify concurrency limitations?

### ISSUE THREAD

**Issue by calmh** [syndtr/goleveldb#55]
The documentation only mentions goroutine-safeness to say that an iterator is not. Is everything else (i.e. concurrent Put()s from separate routines are fine etc)? It would be nice if this was explicitly documented somewhere.

**Comment by libeclipse** [comment]
@syndtr Along what @jaekwon said, I agree that the README.md should mention the concurrency guidelines.

**Comment by syndtr** [comment]
@libeclipse added
