### ISSUE TITLE
resource temporarily unavailable

### ISSUE THREAD

**Issue by scampi** [syndtr/goleveldb#76]
I am trying to test the creation of DB stores. However, I get the error in subject when trying to open a DB (file-based). The DB in question is created by the test code, and so I make sure to close it before.

Would you know what could cause this ?

The relevant code is at https://gitlab.insight-centre.org/ranking/tree-ranking/tree/issue3/data

Thanks

**Comment by gudata** [comment]
> I am trying to test the creation of DB stores. However, I get the error in subject when trying to open a DB (file-based). The DB in question is created by the test code, and so I make sure to close it before.
> 
> Would you know what could cause this ?
> 
> The relevant code is at https://gitlab.insight-centre.org/ranking/tree-ranking/tree/issue3/data
> 
> Thanks

Note ! The relevant code is no more available.

**Comment by hosseinmd** [comment]
Add `ReadOnly: true` to option of `OpenFile` fixed my problem.
