### ISSUE TITLE
Possible corruption on the block data

### ISSUE THREAD

**Issue by syndtr** [syndtr/goleveldb#90]
This could be caused by bug in the `table writer` or `block buffer`.

Corruption on the `block buffer` could be caused by  same buffer acquired more than once from buffer pool by two different `block` instance (or probably added to buffer pool more than once?). 

https://gist.github.com/syndtr/a97bef48b12df8181d6b

Recovering the DB doesn't indicate any corruption but the corrupted table may already been deleted.

Could be related to syncthing/syncthing#987.

**Comment by calmh** [comment]
So... Did you ever get anywhere with this?

**Comment by syndtr** [comment]
Not really, I was able to trigger some corruption using `manualtest/dbstress`, mostly due to bit flip, got some missing keys too (but haven't really got time to inspect it though). Tried on VM (with ECC) for a day, unfortunately cannot trigger corruption, probably the VM not powerful enough.

@AudriusButkevicius Ah, sorry, I forgot your offer, if you could run `manualtest/dbstress` and report back that would be great, it will run forever until a corruption or error triggered or you kill it. Thanks

**Comment by calmh** [comment]
Thanks, I'll do some testing as well.

**Comment by syndtr** [comment]
Great, thanks!

**Comment by AudriusButkevicius** [comment]
Can someone remind me about this on monday?

**Comment by AudriusButkevicius** [comment]
Ok, added a reminder to do this once back from holiday.

**Comment by FlashKnight** [comment]
What will going on if some data block corrupted ? 
is there any way to avoid data lost ? If not , is it possible to backup the old k-v records at run-times?
I am a little worry about this before use in production environment.

**Comment by dc0d** [comment]
Is this got resolved? A two year bug about data loss (for a database) in issues page is daunting for newcomers!

I wanted to use it as underlying kv-store for bleve.

Best;

**Comment by calmh** [comment]
The times we've seen this, we've been able to prove it was bad hardware a number of times and the remaining ones are mysterious but seem tied to specific machines. I've never seen it happen on *known good* hardware.

**Comment by syndtr** [comment]
The corruption I observe so far is due to bit-flip, which is likely hardware related. Issue #128 however still a mystery to me.

I will close this for now, as its most likely hardware related.
