### ISSUE TITLE
Large DB performance

### ISSUE THREAD

**Issue by dim** [syndtr/goleveldb#93]
Hi (again), 

I am debugging a performance problem for a few weeks and simply cannot find a (good) reason for it, so I thought I throw it out there. I have a large database with ~1,200 ldb files and ~60G of uncompressed data. I tried various different settings, including the newly added CompactionTableSize, etc, but I cannot get a reasonable performance from the store. A simple key lookup takes ~40ms mean, despite a fast SSD and only minimal CPU iowait.

I tried the same dataset using https://github.com/tecbot/gorocksdb and I get response times of ~3ms. I added some instrumentation code to measure the individual parts. Initially, I sampled the `DB.get` method, here are some of my measurements (percentiles in µs):

```
mem:ok        cycles:8972 50:7 60:9 70:10 80:12 90:16 95:20 99:29
sst:ok        cycles:4464 50:38685 60:44953 70:52326 80:62153 90:79083 95:96294 99:154369
sst:notfound  cycles:5554 50:45056 60:57278 70:76150 80:99459 90:130868 95:157157 99:213598
```

Obviously memtable lookups are fast, but the disk-based lookups are really quite bad, especially when you look at the 95%'iles. I also tried to benchmark on a lower level by measuring https://github.com/syndtr/goleveldb/blob/9df1f89/leveldb/version.go#L81 (= `walk`) and these 5 lines https://github.com/syndtr/goleveldb/blob/9df1f89/leveldb/version.go#L149 (= `find`). Here is a sample result:

```
walk cycles:4389 50:49594 60:58012 70:69700 80:87999 90:124473 95:152832 99:206840
find cycles:112061 50:48 60:67 70:1460 80:3883 90:8385 95:12777 99:22892
walk cycles:3544 50:38309 60:44003 70:50984 80:58499 90:72621 95:86675 99:126830
find cycles:89412 50:49 60:67 70:850 80:2611 90:6141 95:9889 99:18437
```

It looks like most of the time is spent in `find`, which is called ~30x per `walk` cycle. Does this suggest too many levels? Anything else I haven't considered or I could/should measure or verify? 

Sorry for the length, thanks in advance

**Comment by hit9** [comment]
Hi. @syndtr Dose the LRU issue has been solved now?

**Comment by syndtr** [comment]
I believe so, I rewrote the package a while back. See: 63c9e642efad852f49e20a6f90194cae112fd2ac. I've opened issue for this specific LRU issue here #95, must have forgotten to mention it here.

**Comment by hit9** [comment]
@syndtr Thanks.

My case is, we are running a server on this goleveldb, handling 1.8GB storage, and the time cost to query 600 keys (query 7 times, each time using the iterator for 85 keys) is ~5.7ms. And I think it's a little slow..
